# Exercices séance 05

**Reminder**
* Chacune de vos fonctions doit être testée. 

* Chaque cellule doit compiler. 

* Si le résultat n'est pas celui voulu, expliquer ce qui semble ne pas aller dans votre fonction en commentaires. 


### 1. Ecrire une fonction qui prend une liste de mots et retourne le plus long. Gérer le cas où la liste ne contient pas que des strings.


In [7]:
liste = ['liste', 'de', 'mots', 'longs', 'et', 'moinslongue', 10, 16]

### 2. Ecrire une fonction qui ajoute une string au milieu d'une autre string.


In [10]:
ajouter_au_milieu('moinslongue', ' ')

'moins longue'

### 3. Ecrire une fonction qui transforme en majuscule la première et la dernière lettre de toutes les string d'une liste.


In [39]:
# Test
liste_mots = ["exemple", "python", "programmation"]
resultat = majuscules_premiere_derniere(liste_mots)
print(resultat)

['ExemplE', 'PythoN', 'ProgrammatioN']


### 4. Ecrire une fonction qui trouve les 3 plus hautes valeurs d'un dictionnaire.


In [37]:
# Test
mon_dictionnaire = {'a': 10, 'b': 5, 'c': 8, 'd': 15}
resultat = trois_plus_hautes_valeurs(mon_dictionnaire)
print(resultat)

[15, 10, 8]


### 5. Ecrire une fonction qui ajoute un élément à un tuple. Idem qui enlève.


In [35]:
# Test
tup = (1, 2, 3, 4, 2)
nouvel_element = 2
result_ajout = ajouter_element_tuple(tup, nouvel_element)
result_enlever = enlever_element_tuple(tup, nouvel_element)

print(result_ajout)  # Output: (1, 2, 3, 4, 2, 2)
print(result_enlever)  # Output: (1, 3, 4)


(1, 2, 3, 4, 2, 2)
(1, 3, 4)


### 6. Ecrire une fonction qui remplace la dernière valeur des tuples d'une liste.
	Exemple :
		entree: [(10, 20, 40), (40, 50, 60), (70, 80, 90)]
		sortie: [(10, 20, 100), (40, 50, 100), (70, 80, 100)]


In [33]:
# Test
entree = [(10, 20, 40), (40, 50, 60), (70, 80, 90)]
sortie = remplacer_derniere_valeur(entree, 100)
print(sortie)

[(10, 20, 100), (40, 50, 100), (70, 80, 100)]


### 7. Ecrire une fonction qui lit un csv dont les délimiteurs sont des tabulations (import csv ou pandas).


In [ ]:
tsv =

### 8. Ecrire une fonction qui écrit des dictionnaires dans un fichier (json par exemple)


In [ ]:
import json

In [ ]:
bureau = {'marque': "ikeu", 'matiere': "bois", 'type': "meuble", 'nom': "bureau", 'designeur': "Fernand"}
def dict_to_json():


### 9. Ecrire une fonction qui convertit un array en array de float


In [19]:
import numpy as np

In [20]:
integers = np.arange(1, 15)

In [21]:
integers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
array_float = int_to_float(integers)

In [24]:
type(array_float)

numpy.ndarray

In [25]:
array_float

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.])

### 10. Ecrire une fonction qui enregistre un array dans un fichier texte.


In [30]:
array = np.array([[8,3,2,4],[5,1,6,0],[9,7,4,1]])

In [31]:
array_to_txt_and_display(array)


Content in array_file.txt:
 [[8 3 2 4]
 [5 1 6 0]
 [9 7 4 1]]


### 11. Ecrire une fonction qui réalise l'addition matricielle de deux arrays. La multiplication ça se tente ?

In [14]:
import numpy as np

M = np.array([[1, 2], [3, 4]]) 
N = np.array([[4, 3], [2, 1]]) 

In [15]:
addition_matricielle(M, N)

array([[5, 5],
       [5, 5]])

In [16]:
multiplication_matricielle(M, N)

array([[ 8,  5],
       [20, 13]])