# Exercices séance 05

**Reminder**
* Chacune de vos fonctions doit être testée. 

* Chaque cellule doit compiler. 

* Si le résultat n'est pas celui voulu, expliquer ce qui semble ne pas aller dans votre fonction en commentaires. 


### 1. Ecrire une fonction qui prend une liste de mots et retourne le plus long. Gérer le cas où la liste ne contient pas que des strings.


In [7]:
liste = ['liste', 'de', 'mots', 'longs', 'et', 'moinslongue', 10, 16]

In [12]:
def plus_long(liste_mots):
    mot_long = ''
    for mot in liste_mots:
        if len(str(mot)) > len(mot_long):
            mot_long = mot
    return mot_long

In [11]:
plus_long(liste) 

'moinslongue'

### 2. Ecrire une fonction qui ajoute une string au milieu d'une autre string.


In [8]:
def ajouter_au_milieu(chaine, ajout):
    milieu = len(chaine) // 2
    return chaine[:milieu] + ajout + chaine[milieu:]

In [10]:
ajouter_au_milieu('moinslongue', ' ')

'moins longue'

### 3. Ecrire une fonction qui transforme en majuscule la première et la dernière lettre de toutes les string d'une liste.


In [40]:
def majuscules_premiere_derniere(liste_strings):
    result = []
    for string in liste_strings:
        modified_string = string[0].upper() + string[1:-1] + string[-1].upper()
        result.append(modified_string)
    return result


In [39]:
# Test
liste_mots = ["exemple", "python", "programmation"]
resultat = majuscules_premiere_derniere(liste_mots)
print(resultat)

['ExemplE', 'PythoN', 'ProgrammatioN']


### 4. Ecrire une fonction qui trouve les 3 plus hautes valeurs d'un dictionnaire.


In [36]:
def trois_plus_hautes_valeurs(dictionnaire):
    valeurs = list(dictionnaire.values())
    valeurs.sort(reverse=True)
    return valeurs[:3]


In [37]:

# Test
mon_dictionnaire = {'a': 10, 'b': 5, 'c': 8, 'd': 15}
resultat = trois_plus_hautes_valeurs(mon_dictionnaire)
print(resultat)

[15, 10, 8]


### 5. Ecrire une fonction qui ajoute un élément à un tuple. Idem qui enlève.


In [1]:
def ajouter_element_tuple(tup, element):
    return tup + (element,)

def enlever_element_tuple(tup, element):
    result = []
    for i in tup:
        if i != element:
            result.append(i)
    return tuple(result)


In [2]:

# Test
tup = (1, 2, 3, 4, 2)
nouvel_element = 2
result_ajout = ajouter_element_tuple(tup, nouvel_element)
result_enlever = enlever_element_tuple(tup, nouvel_element)

print(result_ajout)  # Output: (1, 2, 3, 4, 2, 2)
print(result_enlever)  # Output: (1, 3, 4)


(1, 2, 3, 4, 2, 2)
(1, 3, 4)


### 6. Ecrire une fonction qui remplace la dernière valeur des tuples d'une liste.
	Exemple :
		entree: [(10, 20, 40), (40, 50, 60), (70, 80, 90)]
		sortie: [(10, 20, 100), (40, 50, 100), (70, 80, 100)]


In [32]:
def remplacer_derniere_valeur(liste_tuples, nouvelle_valeur):
    result = []
    for tup in liste_tuples:
        modified_tuple = tup[:-1] + (nouvelle_valeur,)
        result.append(modified_tuple)
    return result

In [33]:
# Test
entree = [(10, 20, 40), (40, 50, 60), (70, 80, 90)]
sortie = remplacer_derniere_valeur(entree, 100)
print(sortie)

[(10, 20, 100), (40, 50, 100), (70, 80, 100)]


### 7. Ecrire une fonction qui lit un csv dont les délimiteurs sont des tabulations (import csv ou pandas).


In [ ]:
tsv = pd.read_csv("/chemin/vers/fichier/tsv.csv", delimiter='\t') # tsv.csv n'existe pas, mais cette instruction devrait fonctionner 

### 8. Ecrire une fonction qui écrit des dictionnaires dans un fichier (json par exemple)


In [ ]:
import json

In [ ]:
bureau = {'marque': "ikeu", 'matiere': "bois", 'type': "meuble", 'nom': "bureau", 'designeur': "Fernand"}
def dict_to_json():
    with open('document.json', 'w') as json_file:
        json.dump(bureau, json_file)

### 9. Ecrire une fonction qui convertit un array en array de float


In [19]:
import numpy as np

In [20]:
integers = np.arange(1, 15)

In [21]:
integers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
def int_to_float(array):
    for floating in array:
        floating = integers.astype(float)
    return floating

In [23]:
array_float = int_to_float(integers)

In [24]:
type(array_float)

numpy.ndarray

In [25]:
array_float

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.])

In [26]:
integers = integers.astype(float)

In [27]:
integers

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.])

### 10. Ecrire une fonction qui enregistre un array dans un fichier texte.


In [30]:
array = np.array([[8,3,2,4],[5,1,6,0],[9,7,4,1]])

In [28]:
def array_to_txt_and_display(array):
    
    file = open("array_file.txt", "w+") 
  
    content = str(array) 
    file.write(content) 
    file.close() 
    
    file = open("array_file.txt", "r") 
    content = file.read() 
  
    print("\nContent in array_file.txt:\n", content) 
    file.close() 

In [31]:
array_to_txt_and_display(array)


Content in array_file.txt:
 [[8 3 2 4]
 [5 1 6 0]
 [9 7 4 1]]


### 11. Ecrire une fonction qui réalise l'addition matricielle de deux arrays. La multiplication ça se tente ?

In [14]:
import numpy as np

M = np.array([[1, 2], [3, 4]]) 
N = np.array([[4, 3], [2, 1]]) 

def addition_matricielle(a, b):
    return np.add(a, b)

def multiplication_matricielle(a, b):
    return np.dot(a, b)

In [15]:
addition_matricielle(M, N)

array([[5, 5],
       [5, 5]])

In [16]:
multiplication_matricielle(M, N)

array([[ 8,  5],
       [20, 13]])