## Exercices avec NumPy

### 1 : Création d'un tableau Numpy
**Enoncé :** Créez un tableau Numpy contenant 5 entiers aléatoires entre 1 et 10.

### 2 : Opérations arithmétiques
**Enoncé :** Créez deux tableaux Numpy de même forme (par exemple, 2x3) et effectuez une opération d'addition entre les deux.

### 3 : Indexation et découpage
**Enoncé :** Créez un tableau Numpy 1D et affichez uniquement les éléments dont la valeur est supérieure à 5.

### 4 : Manipulation de forme (reshape)
**Enoncé :** Créez un tableau Numpy 1D avec 12 éléments et modifiez sa forme pour en faire une matrice 3x4.

### 5 : Manipulation avancée
**Enoncé :** Créez une matrice NumPy 3x4 avec des valeurs générées aléatoirement entre 1 et 10. Ensuite, remplacez toutes les valeurs impaires par zéro.



In [1]:
import numpy as np

In [4]:
tableau1 = np.random.randint(1,11,size=5)

In [5]:
tableau1

array([9, 1, 5, 8, 8])

In [13]:
tableau2 = np.full((2, 3),fill_value=2)

In [15]:
tableau3 = np.full((2, 3),fill_value=4)

In [16]:
tableau4 =  tableau2 + tableau3 

In [17]:
tableau4

array([[6, 6, 6],
       [6, 6, 6]])

In [25]:
a = np.array([1, 2, 3, 4, 5, 6,1, 2, 3, 4, 5, 6])

In [23]:
b = a[a>5]

In [24]:
b

array([6, 6, 7])

In [26]:
a.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [38]:
matrix = np.random.randint(1,11, size=(3,4))

In [39]:
matrix

array([[ 2, 10, 10,  1],
       [ 1,  8,  3,  1],
       [ 1,  8,  7,  8]])

In [41]:
matrix%2 == 1

array([[False, False, False,  True],
       [ True, False,  True,  True],
       [ True, False,  True, False]])

In [42]:
matrix%2 != 0

array([[False, False, False,  True],
       [ True, False,  True,  True],
       [ True, False,  True, False]])

In [34]:
matrix[matrix%2 != 0]=0

In [35]:
matrix

array([[ 0,  8,  4,  8],
       [ 0,  4,  0,  0],
       [ 6,  6, 10,  2]])

## Exercices avec Pandas

**Lire le datadrame comme dans le notebook du cours : df_corpus = pd.read_csv('chemin/vers/data_corpus.csv')**

### 1 : Afficher le dataframe du roman 'pauvre blaise'

### 2 : Afficher le dataframe de l'auteur 'romain gary'

### 3 : Afficher le dataframe des auteurs morts avant 1865

### 4 : Afficher le dataframe des autrices femmes qui sont canoniques 

### 5 : Afficher le dataframe des autrices femmes qui sont canoniques avant 1878


In [2]:
import pandas as pd

In [49]:
df_corpus = pd.read_csv('/home/crazyjeannot/Documents/cours/2024/Python4DH/data/csv/data_corpus.csv')

In [7]:
df_corpus.head(2)

doc_name  date             auteur  \
0  1861_Segur-comtesse-de_Pauvre-Blaise  1861  comtesse de segur   
1             1845_Sand-George_Teverino  1845        george sand   

           titre  canon  gender mort_auteur  
0  pauvre blaise  False  female        1874  
1       teverino   True  female        1876

In [11]:
df_corpus.titre=="pauvre blaise"

0        True
1       False
2       False
3       False
4       False
        ...  
2955    False
2956    False
2957    False
2958    False
2959    False
Name: titre, Length: 2960, dtype: bool

In [9]:
df_corpus[df_corpus.titre=="pauvre blaise"]

doc_name  date             auteur  \
0  1861_Segur-comtesse-de_Pauvre-Blaise  1861  comtesse de segur   

           titre  canon  gender mort_auteur  
0  pauvre blaise  False  female        1874

In [33]:
df_gary = df_corpus[df_corpus["auteur"]=="romain gary"]

In [34]:
df_gary

doc_name  date       auteur  \
985                             1972_Gary-Romain_Europa  1972  romain gary   
1298          1981_Gary-Romain_Vie-et-mort-d-Emile-Ajar  1981  romain gary   
1641                  1968_Gary-Romain_La-Tete-coupable  1968  romain gary   
1759                       1970_Gary-Romain_Chien-blanc  1970  romain gary   
1845                      1977_Gary-Romain_Charge-d-ame  1977  romain gary   
1881               1956_Gary-Romain_Les-Racines-du-Ciel  1956  romain gary   
1993               1979_Gary-Romain_Les-clowns-lyriques  1979  romain gary   
2024             1960_Gary-Romain_La-promesse-de-l-aube  1960  romain gary   
2045  1975_Gary-Romain_Au-dela-de-cette-limite-votre...  1975  romain gary   

                                                  titre  canon gender  \
985                                              europa   True   male   
1298                           vie et mort d emile ajar   True   male   
1641                                   la tete coupable   True   male   
1759                                        chien blanc   True   male   
1845                                       charge d ame   True   male   
1881                                les racines du ciel   True   male   
1993                                les clowns lyriques   True   male   
2024                              la promesse de l aube   True   male   
2045  au dela de cette limite votre ticket n est plu...   True   male   

     mort_auteur  
985         1980  
1298        1980  
1641        1980  
1759        1980  
1845        1980  
1881        1980  
1993        1980  
2024        1980  
2045        1980

In [36]:
df_corpus[df_corpus["mort_auteur"]<"1965"]

doc_name  date             auteur  \
0       1861_Segur-comtesse-de_Pauvre-Blaise  1861  comtesse de segur   
1                  1845_Sand-George_Teverino  1845        george sand   
2           1892_Allais-Alphonse_Vive-la-vie  1892    alphonse allais   
4        1894_Rachilde_Le-Demon-de-l-Absurde  1894           rachilde   
6      1913_Leroux-Gaston_La-Reine-du-Sabbat  1913      gaston leroux   
...                                      ...   ...                ...   
2949      1843_Le-Roux-Alfred_Edouard-Aubert  1843     roux alfred le   
2951           1879_Greville-Henry_La-Niania  1879     henry greville   
2956            1910_Zevaco-Michel_Triboulet  1910      michel zevaco   
2957      1880_Gouraud-Julie_Aller-et-retour  1880      julie gouraud   
2959  1845_Sue-Eugene_La-coucaratcha_Tome-II  1845         eugene sue   

                      titre  canon  gender mort_auteur  
0             pauvre blaise  False  female        1874  
1                  teverino   True  female        1876  
2               vive la vie  False    male        1905  
4     le demon de l absurde  False  female        1953  
6        la reine du sabbat  False    male        1927  
...                     ...    ...     ...         ...  
2949         edouard aubert  False    male        1880  
2951              la niania  False  female        1902  
2956              triboulet  False    male        1918  
2957        aller et retour  False  female        1891  
2959         la coucaratcha   True    male        1857  

[2021 rows x 7 columns]

In [40]:
def clean_list(liste_dates):
    liste_clean = []
    for date in liste_dates:
        if str(date)[-1] in ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']:
            liste_clean.append(int(date))
        else:
            liste_clean.append(None)
    return liste_clean

In [52]:
type(list(df_corpus.mort_auteur)[0])

float

In [51]:
df_corpus["mort_auteur"] = clean_list(list(df_corpus.mort_auteur))

In [48]:
df_corpus[df_corpus["mort_auteur"]<1965]

doc_name  date             auteur  \
0       1861_Segur-comtesse-de_Pauvre-Blaise  1861  comtesse de segur   
1                  1845_Sand-George_Teverino  1845        george sand   
2           1892_Allais-Alphonse_Vive-la-vie  1892    alphonse allais   
4        1894_Rachilde_Le-Demon-de-l-Absurde  1894           rachilde   
6      1913_Leroux-Gaston_La-Reine-du-Sabbat  1913      gaston leroux   
...                                      ...   ...                ...   
2949      1843_Le-Roux-Alfred_Edouard-Aubert  1843     roux alfred le   
2951           1879_Greville-Henry_La-Niania  1879     henry greville   
2956            1910_Zevaco-Michel_Triboulet  1910      michel zevaco   
2957      1880_Gouraud-Julie_Aller-et-retour  1880      julie gouraud   
2959  1845_Sue-Eugene_La-coucaratcha_Tome-II  1845         eugene sue   

                      titre  canon  gender  mort_auteur  
0             pauvre blaise  False  female       1874.0  
1                  teverino   True  female       1876.0  
2               vive la vie  False    male       1905.0  
4     le demon de l absurde  False  female       1953.0  
6        la reine du sabbat  False    male       1927.0  
...                     ...    ...     ...          ...  
2949         edouard aubert  False    male       1880.0  
2951              la niania  False  female       1902.0  
2956              triboulet  False    male       1918.0  
2957        aller et retour  False  female       1891.0  
2959         la coucaratcha   True    male       1857.0  

[2003 rows x 7 columns]

In [57]:
df_corpus.canon.value_counts()

canon
False    1806
True     1154
Name: count, dtype: int64

In [59]:
df_canon = df_corpus[(df_corpus["gender"]=='female') & (df_corpus["canon"]==True)]

In [61]:
df = df_canon[df_canon["date"]<1878]

In [62]:
df

doc_name  date  \
1                             1845_Sand-George_Teverino  1845   
17      1866_Sand-George_Promenades-autour-d-un-village  1866   
40                               1844_Sand-George_Andre  1844   
46             1851_Sand-George_Le-chateau-des-Desertes  1851   
193             1845_Sand-George_Le-meunier-d-Angibault  1845   
214                         1855_Sand-George_Kourroglou  1855   
481                              1847_Sand-George_Simon  1847   
514                            1833_Sand-George_Lavinia  1833   
598            1876_Sand-George_Contes-d-une-grand-mere  1876   
600                  1849_Sand-George_La-petite-Fadette  1849   
617                        1859_Sand-George_Elle-et-Lui  1859   
637                        1834_Sand-George_Leone-Leoni  1834   
721                 1865_Sand-George_Monsieur-Sylvestre  1865   
740                            1832_Sand-George_Indiana  1832   
832                 1848_Sand-George_François-le-champi  1848   
862   1871_Sand-George_Journal-d-un-voyageur-pendant...  1871   
940                   1857_Sand-George_Les-dames-vertes  1857   
1066                 1846_Sand-George_Lucrezia-Floriani  1846   
1098                           1837_Sand-George_Mauprat  1837   
1121                          1855_Sand-George_Melchior  1855   
1132                             1872_Sand-George_Nanon  1872   
1161                       1825_Duras-Claire-de_Edouard  1825   
1196                          1875_Sand-George_Marianne  1875   
1302                         1832_Sand-George_Valentine  1832   
1371               1841_Sand-George_Un-hiver-a-Majorque  1841   
1393                1823_Duras-Claire-de-Durfort_Ourika  1823   
1411                1858_Sand-George_Legendes-rustiques  1858   
1575            1853_Sand-George_La-fauvette-du-docteur  1853   
1583                1837_Sand-George_La-derniere-Aldini  1837   
1656  1851_Sand-George_Histoire-du-veritable-Gribouille  1851   
1755                             1864_Sand-George_Laura  1864   
1799  1841_Sand-George_Le-compagnon-du-tour-de-Franc...  1841   
1899                 1846_Sand-George_La-Mare-au-Diable  1846   
2019                           1872_Sand-George_Francia  1872   
2036                           1833_Sand-George_Metella  1833   
2037             1837_Sand-George_Les-maitres-mosaistes  1837   
2064                       1832_Sand-George_La-Marquise  1832   
2068      1877_Sand-George_Mademoiselle-de-la-Quintinie  1877   
2185  1858_Sand-George_Les-beaux-messieurs-de-Bois-D...  1858   
2282              1834_Sand-George_Le-secretaire-intime  1834   
2288                             1833_Sand-George_Lelia  1833   
2405                          1843_Sand-George_Consuelo  1843   
2418              1853_Sand-George_Les-maitres-sonneurs  1853   
2512  1841_Sand-George_Le-compagnon-du-tour-de-Franc...  1841   
2614         1843_Sand-George_La-Comtesse-de-Rudolstadt  1843   
2627             1847_Sand-George_Le-peche-de-M-Antoine  1847   
2645                            1876_Sand-George_Horace  1876   
2758  1858_Sand-George_Les-beaux-messieurs-de-Bois-D...  1858   
2786                           1840_Sand-George_Pauline  1840   
2896            1864_Sand-George_Le-marquis-de-Villemer  1864   

                       auteur                                    titre  canon  \
1                 george sand                                 teverino   True   
17                george sand           promenades autour d un village   True   
40                george sand                                    andre   True   
46                george sand                  le chateau des desertes   True   
193               george sand                   le meunier d angibault   True   
214               george sand                               kourroglou   True   
481               george sand                                    simon   True   
514               george sand                                  lavinia   True   
59

## Exercice de tri

Vous devez implémenter une fonction nommée tri_selection qui prend en paramètre un dictionnaire représentant la fréquence des mots dans un texte. La fonction doit retourner une liste de couple(mots, compte) triée par ordre croissant de la fréquence des mots.

Reprenez l'exercice de la semaine passée, et le dictionnaire obtenu après la fonction compte_mots, mais cette fois ci vous ne pouvez pas utiliser ni de lambda ni la fonction sorted(). utiliser uniquement des boucles for et des conditions if/else/elif

In [79]:
def tri_selection(dictionnaire: dict) -> list: # meme chose que def tri_selection(dictionnaire):
    """
    Trie un dictionnaire de fréquence de mots par ordre croissant de fréquence.

    Args:
    - dictionnaire (dict): Un dictionnaire où les clés sont des mots et les valeurs sont leur fréquence d'apparition.

    Returns:
    - list: Une liste de tuples (mot, fréquence) triée par ordre croissant de la fréquence des mots.
    """
    # Votre code ici

    liste_elem = list(dictionnaire.keys())
    n = len(liste_elem)

    assert(type(liste_elem)==list)
    
    for i in range(n):
        echanger = False
        for j in range(0, n-1-i):
            if dictionnaire[liste_elem[j]] < dictionnaire[liste_elem[j+1]]:
                liste_elem[j], liste_elem[j+1] = liste_elem[j+1], liste_elem[j]
                echanger = True
        if echanger==False:
            break

    
    return liste_elem

In [80]:
list(freq_mots.keys())

['chat', 'chien', 'oiseau']

In [81]:
def compte_mots(liste_mots):
    mots_comptes = {}
    for mot in liste_mots:
        if mot in mots_comptes:
            mots_comptes[mot] += 1
        else:
            mots_comptes[mot] = 1
    return mots_comptes

In [95]:
def main(chemin_fichier, N=10, M=10):
    with open(chemin_fichier, 'r') as file:
        contenu = file.read().lower().split()

    mots_comptes = compte_mots(contenu)
    mots_tries = sorted(mots_comptes.keys(), key=mots_comptes.get)

    mots_plus_freq = mots_tries[-N:]
    mots_moins_freq = mots_tries[:M]

    sauvegarde(mots_moins_freq, mots_plus_freq)
    return mots_plus_freq, mots_moins_freq, mots_comptes

In [92]:
def sauvegarde(mots_peu_frequents, mots_tres_frequents):
    with open("mots_peu_frequents.txt", "w") as fichier_peu_freq:
        for mot in mots_peu_frequents:
            fichier_peu_freq.write(f"{mot}\n")

    with open("mots_tres_frequents.txt", "w") as fichier_tres_freq:
        for mot in mots_tres_frequents:
            fichier_tres_freq.write(f"{mot}\n")

In [90]:
chemin_fichier = "/home/crazyjeannot/Documents/cours/2024/Python4DH/data/txt/1841_Sand-George_Un-hiver-a-Majorque.txt"

In [96]:
mots_plus_freq, mots_moins_freq, mots = main(chemin_fichier, 16, 2)

In [85]:
import timeit

In [97]:
# test de la fonction : 
start_time_sorted = timeit.default_timer()
mots_plus_freq, mots_moins_freq, mots = main(chemin_fichier, 50, 50)
elapsed_time_sorted = timeit.default_timer() - start_time_sorted
print(f"Time taken by sorted(): {elapsed_time_sorted:.6f} seconds")


Time taken by sorted(): 0.010370 seconds
